### PR TITLE
Fix off-by-one error in loop support

### LINKED ISSUE #61: Loop support - slight bursts, maybe still not aligned etc?
DereTore.Applications 0.8.1.176

I can see small gaps between joined looping audio clips, if the waveform is sufficiently magnified.

https://github.com/Nyagamon/HCADecoder produced a file with seemingly incorrect length - however I can't find such gap.

### PR DESCRIPTION
**Pull request by segfault-bilibili**
~Not tested.~ Not heavily tested.

Fix #61

### CODE REVIEW

**Comment by segfault-bilibili** [comment]
Unfixed "seam" (at loop end + 1 block offset)

Unfixed

--------

Fixed "seam" (at loop end + 0 block offset)

Fixed

--------

Original, the right half "tail" has not yet been overwritten by the loop start block (at loop end + 0 block offset)

Orig

**Comment by segfault-bilibili** [comment]
@CaiMiao

**Comment by hozuki** [comment]
LGTM.

Thanks for the fix! I don't have plenty of looped audios to test. The test results above proves itself.

**Comment by hozuki** [comment]
Hmm CI seems failing. I'll try to fix that when not occupied.

**Comment by segfault-bilibili** [comment]
>I don't have plenty of looped audios to test.

You may try Magia Record.

>Hmm CI seems failing.

Hmm? Seems to be okay for me: https://ci.appveyor.com/project/segfault-bilibili/deretore/builds/42691233

**Comment by segfault-bilibili** [comment]
I did nothing than authorizing AppVeyor as a GitHub app and then authorizing it to access my forked repo. Maybe you can just try to revoke access permissions for AppVeyor and then re-grant it in GitHub?

**Comment by segfault-bilibili** [comment]
However I saw an error in the build log, not sure whether this matters:

https://ci.appveyor.com/project/segfault-bilibili/deretore/builds/42691233?fullLog=true#L234

```
WARNING: NU1603: Build depends on Cake.Frosting (>= 0.1.0-alpha0078) but Cake.Frosting 0.1.0-alpha0078 was not found. An approximate best match of Cake.Frosting 0.31.0 was resolved.
  NotFound https://www.myget.org/F/cake/api/v3/flatcontainer/system.security.accesscontrol/index.json 2201ms
nuget : NU1605: Detected package downgrade: Cake.Common from 0.31.0 to 0.28.0. Reference the package directly from the project to select a different version. 
At line:1 char:1
+ nuget restore "C:\projects\deretore\external\VGAudio\build\Build.sln"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (NU1605: Detecte...erent version. :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
 Build -> Cake.Frosting 0.31.0 -> Cake.Common (>= 0.31.0) 
 Build -> Cake.Common (>= 0.28.0)
Committing restore...
Generating MSBuild file C:\projects\deretore\external\VGAudio\build\obj\Build.csproj.nuget.g.props.
Generating MSBuild file C:\projects\deretore\external\VGAudio\build\obj\Build.csproj.nuget.g.targets.
Writing assets file to disk. Path: C:\projects\deretore\external\VGAudio\build\obj\project.assets.json
Failed to restore C:\projects\deretore\external\VGAudio\build\Build.csproj (in 4.2 sec).
Errors in C:\projects\deretore\external\VGAudio\build\Build.csproj
    NU1605: Detected package downgrade: Cake.Common from 0.31.0 to 0.28.0. Reference the package directly from the project to select a different version.
     Build -> Cake.Frosting 0.31.0 -> Cake.Common (>= 0.31.0)
     Build -> Cake.Common (>= 0.28.0)
NuGet Config files used:
```

**Comment by segfault-bilibili** [comment]
There's another bug to be fixed: #63

**Comment by segfault-bilibili** [comment]
At least the "seam" block (at the start of looped blocks) itself should be re-decoded. I'm not sure whether more blocks should be re-decoded, however the affected bytes didn't seem to enough to make a full block - in other words, reworking one block seems to be enough to make the output byte-to-byte exactly the same to "stupidly" decoding every block including looped ones.

**Comment by segfault-bilibili** [comment]
Again I feel very sorry but I think my incorrect patch should be reverted.

**Pull request merged**
